using Godot;
using System.Text;
using System.Collections.Generic;

// ============================================================================
// GraphExporter.cs — 蓝图图导出器
//
// 职责：
//   将编辑器中的当前蓝图图（节点+连接）导出为 .txt 文件。
//   输出格式遵循 graph_format_spec.md 规范。
//
// 使用方式：
//   exporter.ExportToFile("res://exports/my_graph.txt", editorCanvas, connectionManager);
//   或在上下文菜单中点击"导出图..."
// ============================================================================

/// <summary>蓝图图导出器。</summary>
public static class GraphExporter
{
    // ────────────────────────────────────────────────────────────────
    // 导出到文件
    // ────────────────────────────────────────────────────────────────

    /// <summary>
    /// 将当前编辑器的蓝图图导出到 .txt 文件。
    /// </summary>
    /// <param name="filePath">导出文件路径。</param>
    /// <param name="editorCanvas">编辑器画布，提供 ComponentLayer 和 ConnectionLayer。</param>
    /// <param name="connectionManager">连接管理器，提供连接数据。</param>
    /// <param name="graphName">图名称，会写入元数据。</param>
    /// <returns>是否成功。</returns>
    public static bool ExportToFile(
        string filePath,
        EditorCanvas editorCanvas,
        ConnectionManager connectionManager,
        string graphName = "Untitled Blueprint Graph")
    {
        var sb = new StringBuilder(4096);

        // ── 文件头 ──
        sb.AppendLine("# ============================================================");
        sb.AppendLine($"# Blueprint Graph Export - {graphName}");
        sb.AppendLine("# Generated by UE-Blue Blueprint Tool (Godot 4 C#)");
        sb.AppendLine($"# Date: {System.DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine("# ============================================================");
        sb.AppendLine();

        // ── 元数据 ──
        sb.AppendLine($"[Meta] graph_name=\"{graphName}\"");
        sb.AppendLine($"[Meta] graph_version=\"1.0\"");
        sb.AppendLine($"[Meta] node_count=\"{editorCanvas.ComponentLayer.GetChildCount()}\"");
        sb.AppendLine();

        // ── 节点导出 ──
        // 同时建立 componentId → 端口名称映射（用于连接导出）
        var nodeIndexMap = new Dictionary<int, int>(); // componentId → fileNodeId
        var portNameMap  = new Dictionary<(int, int), string>(); // (componentId, portId) → portName
        int fileNodeId = 1;

        foreach (Node child in editorCanvas.ComponentLayer.GetChildren())
        {
            if (child is not BlueprintComponent comp) continue;

            int compId = comp.ComponentId;
            nodeIndexMap[compId] = fileNodeId;

            // 节点类型映射
            string typeStr = comp.Type switch
            {
                ComponentData.ComponentType.OutputOnly => "EventNode",
                ComponentData.ComponentType.InputOnly => "EndNode",
                ComponentData.ComponentType.Dual => comp is TestComponent ? "TestComponent" : "ProcessNode",
                _ => "GenericNode"
            };

            // 覆盖类型名：如果用工厂创建的自定义节点，用 ComponentName 作为类型
            string effectiveType = typeStr;

            sb.AppendLine($"[Node] id={fileNodeId} type={effectiveType} "
                + $"name=\"{comp.ComponentName}\" "
                + $"pos=({comp.Position.X:F1},{comp.Position.Y:F1}) "
                + $"color={HeaderColorToHex(comp.HeaderColor)}");

            // ── 输入端口 ──
            foreach (var pw in comp.GetInputPortWidgets())
            {
                sb.AppendLine($"  IN:{pw.PortDefinition.PortName}|{pw.PortDefinition.PortType}");
                portNameMap[(compId, pw.PortDefinition.PortId)] = pw.PortDefinition.PortName;
            }

            // ── 输出端口 ──
            foreach (var pw in comp.GetOutputPortWidgets())
            {
                sb.AppendLine($"  OUT:{pw.PortDefinition.PortName}|{pw.PortDefinition.PortType}");
                portNameMap[(compId, pw.PortDefinition.PortId)] = pw.PortDefinition.PortName;
            }

            sb.AppendLine();
            fileNodeId++;
        }

        // ── 连接导出 ──
        sb.AppendLine("# ────────────────────────────────────────────────");
        sb.AppendLine("# 连接关系");
        sb.AppendLine("# ────────────────────────────────────────────────");
        sb.AppendLine();

        foreach (Node child in editorCanvas.ComponentLayer.GetChildren())
        {
            if (child is not BlueprintComponent comp) continue;
            var conns = connectionManager.GetConnectionsForComponent(comp.ComponentId);

            foreach (var conn in conns)
            {
                bool isSource = conn.SourceComponentId == comp.ComponentId;
                if (!isSource) continue; // 只从源端输出一次

                if (!nodeIndexMap.TryGetValue(conn.SourceComponentId, out int srcNodeId)) continue;
                if (!nodeIndexMap.TryGetValue(conn.TargetComponentId, out int tgtNodeId)) continue;

                portNameMap.TryGetValue((conn.SourceComponentId, conn.SourcePortId), out string srcPortName);
                portNameMap.TryGetValue((conn.TargetComponentId, conn.TargetPortId), out string tgtPortName);
                srcPortName ??= "?";
                tgtPortName ??= "?";

                sb.AppendLine($"[Connection] {srcNodeId}:{srcPortName} → {tgtNodeId}:{tgtPortName}");
            }
        }

        sb.AppendLine();
        sb.AppendLine("# === End of Graph ===");

        // ── 写入文件 ──
        try
        {
            using var file = FileAccess.Open(filePath, FileAccess.ModeFlags.Write);
            if (file == null)
            {
                GD.PushError($"[GraphExporter] Cannot write to file: {filePath}");
                return false;
            }
            file.StoreString(sb.ToString());
            file.Close();
            GD.Print($"[GraphExporter] Graph exported to: {filePath}");
            return true;
        }
        catch (System.Exception e)
        {
            GD.PushError($"[GraphExporter] Export failed: {e.Message}");
            return false;
        }
    }

    // ────────────────────────────────────────────────────────────────
    // 工具方法
    // ────────────────────────────────────────────────────────────────

    private static string HeaderColorToHex(Color color)
    {
        return string.Format("#{0:X2}{1:X2}{2:X2}",
            (int)(color.R * 255),
            (int)(color.G * 255),
            (int)(color.B * 255));
    }
}
